//
// Created by ClaraUni on 08/06/2020.
//

#ifndef P4_PC_JOYSTICK2_HABITACION_CONTROLLER_H
#define P4_PC_JOYSTICK2_HABITACION_CONTROLLER_H

void autonomous_movement();

#endif //P4_PC_JOYSTICK2_HABITACION_CONTROLLER_H
